baseURL = "https://www.econ-ds.com"
languageCode = "en-us"
title = "Coding Proof Coffee"
#publishDir = "docs"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  customCSS = ["custom.css"]


  [params.homepage]
    show_call_box = true

  [params.logo]
    mobile = "images/logo/logo.svg"
    desktop = "images/logo/logo.svg"
    desktop_height = "140px"
    alt = "Coffee and Code"

  [params.homepage_meta_tags]
    meta_description = "Coffee and Code is the homebase for reading material for your coffee break and revolves around Data Science and Economics."
    meta_og_title = "Hugo Serif Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Coffee and Code is the homebase for reading material for your coffee break and revolves around Data Science and Economics."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.footer]
    copyright_text = 'Blog by <a class="zerostatic" href="https://github.com/finnoh">Finn Hoener - 2020</a>'
  
  

[menu]
  # Main Menu

  [[menu.main]]
      name = "Articles"
      url = "/services/"
      weight = 1
      
  [[menu.main]]
      name = "Tutorials"
      url = "/tutorials/"
      weight = 2


  # Footer Menu

[[menu.footer]]
  name = "Imprint"
  url = "/imprint/"
  weight = 2

[[menu.footer]] 
  name = "Privacy"
  url = "/privacy/"
  weight = 3
