theme = "hugo-serif-theme"
baseURL = "https://coffee-and-code.netlify.app"
#publishDir = "docs"
languageCode = "en-us"
title = "Share and connect."
# ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
