theme = "hugo-serif-theme"
baseURL = "https://ds-econ.netlify.app/"
#publishDir = "docs"
languageCode = "en-us"
title = "Share and connect."
# ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true