theme = "hugo-serif-theme"
baseURL = "https://finnoh.github.io/coffeeandcode/"
languageCode = "en-us"
title = "Share and connect."
# ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
publishDir = "docs"